name: Create bump version PR

on:
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  bump-version-pr:
    name: Bump version PR
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        uses: ./.github/actions/prepare-install
        with:
          node-version: ${{ matrix.node-version }}

      - name: Pre build ckeck
        run: pnpm build

      - name: Create Pull Request
        uses: changesets/action@v1
        with:
          version: pnpm publish-version
          commit: 'chore: version'
          title: 'chore: version'
          setupGitUser: true
          createGithubReleases: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
