name: Create bump version PR

on:
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  bump-version-pr:
    name: Bump version PR
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        uses: ./.github/actions/prepare-install
        with:
          node-version: ${{ matrix.node-version }}

      - name: Pre build ckeck
        run: pnpm build

      - name: Create Version Pull Request
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm publish-version
          commit: 'chore: version'
          title: 'chore: version'
          setupGitUser: true
          createGithubReleases: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: No changesets
        if: steps.changesets.outputs.hasChangesets == 'false'
        run: |
          echo "::error title=No changesets found::All changesets are empty, not creating PR, please add changeset"
          exit 1

      - name: Created Pull Request
        if: steps.changesets.outputs.hasChangesets == 'true'
        run: |
          echo "::notice title=PR is created::Created bump version PR address is: https://github.com/${{github.repository}}/pull/${{steps.changesets.outputs.pullRequestNumber}}"
